# Generated by Django 5.2.13 on 2026-04-12 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbehaviorscore',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='EmpowermentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy_name', models.CharField(max_length=120)),
                ('redirected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('round_up_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('behavioral_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('goal_boost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rationale', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empowerment_allocation', to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empowerment_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='finance_emp_user_id_8a195a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrowthScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.FloatField(default=0)),
                ('budgeting_score', models.FloatField(default=0)),
                ('investing_score', models.FloatField(default=0)),
                ('savings_score', models.FloatField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('resilience_score', models.FloatField(default=0)),
                ('momentum_score', models.FloatField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_score_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='finance_gro_user_id_2438a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavingsTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('round_up', 'Round Up Sweep'), ('subscription', 'Subscription Leak'), ('weekend', 'Weekend Guardrail'), ('goal', 'Goal Gap'), ('payday', 'Payday Sweep')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('recommended_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_impact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_triggers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommended_amount', '-created_at'],
                'indexes': [models.Index(fields=['user', 'trigger_type', 'is_active'], name='finance_sav_user_id_14b0fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='WealthMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_type', models.CharField(choices=[('redirected', 'Redirected Capital'), ('growth_score', 'Growth Score'), ('goal_progress', 'Goal Progress'), ('emergency', 'Emergency Buffer')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('progress_percentage', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('achieved', 'Achieved')], db_index=True, default='active', max_length=20)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('celebration_copy', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wealth_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-progress_percentage', '-created_at'],
                'indexes': [models.Index(fields=['user', 'milestone_type', 'status'], name='finance_wea_user_id_bb0506_idx')],
            },
        ),
    ]
