# Generated by Django 5.2.13 on 2026-04-12 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_userbehaviorscore_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['deadline', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.CreateModel(
            name='WealthSweepRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('round_up', 'Round-Up'), ('cashback_only', 'Cashback Only'), ('hybrid', 'Hybrid'), ('percent', 'Percent of Spend')], default='hybrid', max_length=30)),
                ('round_up_base', models.PositiveIntegerField(default=50)),
                ('spend_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('auto_fund_enabled', models.BooleanField(default=True)),
                ('redirect_cashback_enabled', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('razorpay', 'Razorpay')], default='mock', max_length=30)),
                ('provider_customer_id', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wealth_sweep_rule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WealthContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('round_up', 'Round-Up'), ('cashback', 'Cashback'), ('percent', 'Percent of Spend'), ('manual', 'Manual'), ('reward', 'Reward')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('pending', 'Pending Payment'), ('funded', 'Funded'), ('mock_funded', 'Mock Funded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=30)),
                ('provider', models.CharField(default='mock', max_length=30)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('strategy_name', models.CharField(blank=True, max_length=120)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider_order_id', models.CharField(blank=True, max_length=120)),
                ('provider_payment_id', models.CharField(blank=True, max_length=120)),
                ('provider_signature', models.CharField(blank=True, max_length=255)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(default=dict)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wealth_contributions', to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wealth_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='finance_wea_user_id_d60040_idx'), models.Index(fields=['user', 'source_type', 'created_at'], name='finance_wea_user_id_659f9f_idx')],
            },
        ),
    ]
